# Generated by Django 5.0.3 on 2024-03-04 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last_queue_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Queue Type',
            },
        ),
        migrations.CreateModel(
            name='Limiter_rt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('identity', models.CharField(default='', max_length=64)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('f', 'offline'), ('o', 'online'), ('s', 'syncing')], default='f', max_length=7)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Limiter Router',
            },
        ),
        migrations.CreateModel(
            name='Last_queues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=180)),
                ('max_limit', models.CharField(max_length=24)),
                ('burst_limit', models.CharField(max_length=24)),
                ('burst_threshold', models.CharField(max_length=24)),
                ('burst_time', models.CharField(max_length=24)),
                ('limit_at', models.CharField(max_length=24)),
                ('priority', models.CharField(max_length=24)),
                ('bucket_size', models.CharField(max_length=24)),
                ('parent', models.CharField(max_length=24)),
                ('disabled', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routers.last_queue_types')),
            ],
            options={
                'verbose_name': 'Simple Queue',
            },
        ),
        migrations.CreateModel(
            name='Queue_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=50)),
                ('limiter_rt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routers.limiter_rt')),
            ],
            options={
                'verbose_name': 'Per Router Queue Type',
            },
        ),
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=180)),
                ('max_limit', models.CharField(max_length=24)),
                ('burst_limit', models.CharField(max_length=24)),
                ('burst_threshold', models.CharField(max_length=24)),
                ('burst_time', models.CharField(max_length=24)),
                ('limit_at', models.CharField(max_length=24)),
                ('priority', models.CharField(max_length=24)),
                ('bucket_size', models.CharField(max_length=24)),
                ('queue', models.CharField(max_length=24)),
                ('parent', models.CharField(max_length=24)),
                ('disabled', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3)),
                ('limiter_rt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routers.limiter_rt')),
            ],
            options={
                'verbose_name': 'Per Router Simple Queue',
            },
        ),
    ]
