# Generated by Django 5.0.2 on 2024-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Last_Queues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('target', models.CharField(max_length=180)),
                ('max_limit', models.CharField(default='1/1', max_length=24)),
                ('disabled', models.CharField(max_length=3)),
                ('source_g', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Simple Queues All Locations',
            },
        ),
        migrations.CreateModel(
            name='Global_Limiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('identity', models.CharField(default='', max_length=64)),
                ('source_g', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "Limiter Router's All Locations",
            },
        ),
    ]
