# Generated by Django 5.1 on 2024-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Last_Queues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('target', models.CharField(max_length=180)),
                ('max_limit', models.CharField(default='1/1', max_length=24)),
                ('disabled', models.CharField(max_length=3)),
                ('source_g', models.CharField(max_length=50, verbose_name='Source Group')),
            ],
            options={
                'verbose_name': 'All Simple Queues',
                'ordering': ['source_g'],
            },
        ),
        migrations.CreateModel(
            name='Global_Limiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('identity', models.CharField(default='', max_length=64)),
                ('source_g', models.CharField(max_length=50, verbose_name='Source Group')),
            ],
            options={
                'verbose_name': 'All Limiter Router',
            },
        ),
    ]
